strukturag/spreed-webrtc

.travis.yml
Update travis `install:` to install npm packages locally. 
Fixes requiring of a global package. Travis uses [nvm](https://github.com/creationix/nvm). nvm [corrected](https://github.com/creationix/nvm/issues/586) [NODE_PATH](http://nodejs.org/api/modules.html#modules_loading_from_the_global_folders) environment variable which allowed requiring of global packages.
=> Update travis npm install.

static/js/directives/odfcanvas.js, static/js/directives/pdfcanvas.js
This further improves security.
=> No need for "allow-same-origin" in presentation sandboxes.

src/app/spreed-webrtc-server/roomworker.go
`roomWorker.GetUsers` returns the users in the current and the global room. These got duplicated if the current room was the global room.
=> Don't return users twice in "Welcome" from global room.

static/js/controllers/uicontroller.js, static/js/services/alertify.js
As of now the `webrtcUnsupported.html` custom dialog type is supported. To customize the used template simply write over the `$templateCache` at `/dialogs/webrtcUnsupported.html` from a plugin.
=> Support alertify dialogs of custom type

Godeps
Updated:
- github.com/gorilla/mux
- github.com/gorilla/securecookie
- github.com/gorilla/websocket
- github.com/satori/go.uuid
- github.com/strukturag/phoenix
Also the packages on https://launchpad.net/~strukturag/+archive/ubuntu/spreed-webrtc-dev have been updated.
=> Update dependencies to latest versions.

static/js/directives/screenshare.js, static/js/services/videowaiter.js
The `peercall` event `remoteStreamAdded` can be triggered twice and at times without stream information.  Handle cases when the event is triggered with [null](https://github.com/strukturag/spreed-webrtc/commit/a44cedc52d7495573747c4791f34e6655467cd86#diff-22b49df16d07524e035cc6f8b9e39af7R155).
This PR fixes `undefined` errors and multiple screensharing screens being appended for a stream.
=> Improve handling of peercall event remoteStreamAdded

static/js/libs/ua-parser.js
Update ua-parser.js to [0.7.9](https://github.com/faisalman/ua-parser-js/commits/0.7.9). Use new property `$.ua`, initialized on jquery, to avoid the overhead of creating other new ua instances.
=> Update ua-parser to 0.7.9

.travis.yml
This is executed when building packages, so should be also covered by Travis.
=> Also run "make test" in Travis.

package.json
Autoprefixer has moved to using the [postcss-cli](https://github.com/postcss/postcss). Limit upper version to keep `autoprefixer` binary and move to postcss-cli at a later time.
=> Fix autoprefixer

.javascript_ignore
Hound should not run jshint under `js/static/libs/` or its subfolders. See http://jshint.com/docs/cli/ under ignoring files.
=> Have hound ignore subfolders of js/static/libs/

Makefile.am
This way packaging can later move the static assets to a separate package.
=> Split "install" and "release" targets

static/js/controllers/uicontroller.js, static/js/directives/audiovideo.js, static/js/mediastream/peercall.js, static/js/mediastream/peerconference.js, static/js/mediastream/webrtc.js
There was a case where a three-party conference got downgraded to a p2p session and then upgraded to a three-party conference again, that the two remaining participants created their own PeerConference object resulting in a "split-brain" conference.
Looks like this also fixes #282.
=> Make conferences more consistent

go/channelling/tickets.go, go/channelling/tickets_test.go
The session ids contain a Gorilla SecureCookie which internally encodes
"timestamp|value". As a result, newer session ids compare "greater"
than older ids. This is a problem for conferences where the participants
decide based on comparison of the session id who calls who, so later
participants always have to call all of the existing participants.
With this change, the (random) value is at the start of the session id,
resulting in "random" ordering of participants. Also some tests have
been added to check session en-/decoding.
=> Reverse data in session ids.

static/js/controllers/statusmessagecontroller.js, static/js/controllers/uicontroller.js, static/js/directives/buddylist.js, static/js/mediastream/peercall.js, static/js/mediastream/peerconference.js, static/js/mediastream/peerconnection.js, static/js/mediastream/webrtc.js
Removed difference between single peer-to-peer calls and conferences
with multiple peers. There is only a single code path now that creates
calls and stores them in a conference (which holds all active calls).
With this also fixed some timing issues that could cause conference
peers to not send or receive media streams.
Should help with some of the issues reported in #276.
=> Major refactoring of call / conference handling.

go/channelling/session.go, static/js/controllers/uicontroller.js
Previously, each user broadcasted the status after a "Room" event was
received. This caused a short time for all other participants where
the buddy list showed "Participant X" instead of the real user name.
=> Include user status in "Joined" event.

static/js/controllers/uicontroller.js, static/js/directives/audiovideo.js, static/js/mediastream/peerconference.js, static/js/mediastream/webrtc.js
- Don't show "Failed to establish" message if connection was already established before.
- Don't add empty video component if call was already closed.
- Try to recover from (some) lost p2p connection state (see https://github.com/strukturag/spreed-webrtc/commit/c8763deb58d75ad537fd94771185cb370e9c1833 for details).
- Fix moving between conference rooms (was not working, reported in #276)
=> Various fixes to conference error handling

autogen.sh
For source tarballs, the `.git/hooks` folder does not exist, so an error
is shown when running `autogen.sh`. With this change, the hook is not
installed in such cases.
Saw this in #300 (but is not causing the problem reported there).
=> Only install git hook if cloned from git.

.gitignore, go/channelling/context.go, html/head.html, html/main.html, server.conf.in, src/app/spreed-webrtc-server/handler_room.go, src/app/spreed-webrtc-server/main.go, src/app/spreed-webrtc-server/utils.go
To allow muliple plugins, sorted plugin load and general extensibility
of the web client, the server now supports to load an extra.d folder on
startup.
Sub folders inside extra.d, are loaded in alphabetic order and searched
for head.html and body.html, making it possible to append additional
html code into the <head> and <body> elements for the web client.
Example:
```
extra.d/
└── my-plugin
   ├── body.html
   ├── head.html
   └── static
       ├── css
│   └── my-plugin.css
       └── js
           └── my-plugin.js
```
Example head.html:
```
<link rel="stylesheet" href="<%.S%>/css/my-plugin.css">
```
Example body.html:
```
<script data-plugin="<%.S%>/js/my-plugin.js"></script>
```
This makes it possible to extend the web client with additional
components and/or overwrite existing.
=> Add support for extra.d directory

go/channelling/server/users.go
Issue was introduced in https://github.com/strukturag/spreed-webrtc/commit/a46f36fd486cfef51b3ed53fa2faefdb01ace81f
=> Compare HMACs in constant time to mitigate timing attack

Dockerfile.build, Dockerfile.run, README.md, scripts/docker_entrypoint.sh
To reduce the Docker image size a seperate build Dockerfile is
introduced. This Docker image produces a tarball of the released and
compiled software which can when be piped into the Dockerfile.run build
process. The result is a minimal image only containing Spreed WebRTC and
the gear to run OpenSSL.
First create the builder image:
```
docker build -t spreed-webrtc-builder -f Dockerfile.build .
```
Next run the builder container, piping its output into the creation of
the runner container:
```
docker run --rm spreed-webrtc-builder | docker build -t spreed-webrtc -f
Dockerfile.run -
```
Afterwards run the container like this:
```
docker run --rm --name my-spreed-webrtc -p 8080:8080 -p 8443:8443 \
-v `pwd`:/srv/extra -i -t spreed-webrtc
```
=> Add Dockerfiles to build minimal Docker

scripts/docker_entrypoint.sh
Makes it easier to set shared secrets when running the docker container
Any secret not specified will still be randomly generated as before
cc @longsleep
=> Allow specifying docker secrets with enviroment variables

dependencies.tsv, go/channelling/bus_manager.go, go/natsconnection/natsconnection.go, server.conf.in, src/app/spreed-webrtc-server/main.go
On server startup the configuration files are loaded as normal. NATS is connected first and if enabled, additional configuration is loaded with a NATS request. This makes it possible to provide additional configuration from other services. NATS configuration is only loaded on startup. So whenever the NATS configuration provider changes the webrtc configuration, it has to trigger a restart of Spreed WebRTC externally.
=> Implement config loading via NATS

scripts/docker_entrypoint.sh
=> Docker: Use /dev/urandom instead of /dev/random

static/js/mediastream/peercall.js, static/js/mediastream/webrtc.js
This fixes #377 where no ringing sound was played back because the call
was not seen as "outgoing" (and also fixes the missing timeout if the
called peer does not pick up).
=> Explicitly pass "outgoing" flag when creating PeerCall object.

html/head.html, src/app/spreed-webrtc-server/main.go
Using the latest Go 1.8 beta (0b2daa56), this is what's output in the `script#globalcontext`:
`{main 0xc420083080 spreed-webrtc-test:7443 true false [de-de de en-us en zh-cn zh]  https  static/ver=1480602944  }`
Go has apparently modified their template system: Objects in templates are no longer JSON-encoded by default. Using this fix, Spreed WebRTC even works when compiled with Go 1.8 :)
=> Fix Go 1.8 compatibility

go/channelling/config.go, go/channelling/hub.go, go/channelling/server/config.go, server.conf.in
This is required for cases where an external TURN service should be used that only supports authentication with username/password (but not with a shared secret).
=> Support fixed username/password TURN credentials.

go/channelling/turnservice_manager.go
That way the ordering of the list as received from the server doesn't matter.
=> Use TURN service URNs with lowest priority instead of first in list.

Dockerfile
Current docker build output: /bin/sh: 1: locale-gen: not found
Locale-gen is not provided anymore by ubuntu base image, so it must be installed beforehand.
=> fix broken docker build
