- static/js/directives/youtubevideo.js
Use "safeApply" as deferred can be resolved inside angular.js.
> Fix broken YouTube integration

- static/js/libs/sjcl.js
- static/js/main.js
Diff from [1.0.0 to 1.0.1](https://github.com/bitwiseshiftleft/sjcl/compare/1.0.0...1.0.1).
Diff from [1.0.1 to 1.0.2](https://github.com/bitwiseshiftleft/sjcl/compare/1.0.1...1.0.2).
Built with `./configure --without-all --with-sha256 --with-sha512 --with-sha1 --with-hmac --with-codecBase64 --with-codecString --with-aes --with-ccm --with-convenience --compress=none`
> Update sjcl.js to 1.0.2.

- src/styles/components/_audiovideo.scss
- src/styles/components/_presentation.scss
- src/styles/components/_youtubevideo.scss
- src/styles/global/_overlaybar.scss
- static/partials/youtubevideo.html
Avoid qualifying attribute selectors with an element.
> Fix scss-lint error QualifyingElement

- src/styles/components/_buddylist.scss
- src/styles/components/_buddypictureupload.scss
- src/styles/global/_pages.scss
Nesting should be no greater than 3, but was 4
> Fix scss-lint error NestingDepth

- src/styles/components/_chat.scss
- static/js/controllers/chatroomcontroller.js
- static/partials/picturehover.html
When in a group chat you can now hover over the buddyPicture of someone to call or personally chat with them.
> Add group chat buddyPicture hover functionality

- html/logo.html
- src/styles/components/_audiovideo.scss
- src/styles/components/_bar.scss
- src/styles/components/_buddylist.scss
- src/styles/components/_contactsmanager.scss
- src/styles/components/_fileinfo.scss
- src/styles/components/_presentation.scss
- src/styles/components/_youtubevideo.scss
Selector should have depth of applicability no greater than 3.
> Fix scss-lint  error SelectorDepth

- src/styles/components/_audiovideo.scss
- src/styles/components/_buddylist.scss
- src/styles/components/_buddypicturecapture.scss
- src/styles/components/_buddypictureupload.scss
- src/styles/components/_chat.scss
- src/styles/components/_fileinfo.scss
- src/styles/components/_presentation.scss
- src/styles/components/_rightslide.scss
- src/styles/components/_roombar.scss
- src/styles/components/_screenshare.scss
- src/styles/components/_settings.scss
- src/styles/components/_usability.scss
- src/styles/components/_youtubevideo.scss
- src/styles/global/_overlaybar.scss
The following errors still need to be delt with and decided by @longsleep. When merging selectors you tend to then go in the direction of creating `NestingDepth` errors when the depth exceeds 3. I would leave `_bar.scss` and `_buddylist.scss` as they are because readability is good.
```
components/_bar.scss:33 [W] MergeableSelector: Merge rule `.bar .left` with rule on line 22
components/_bar.scss:69 [W] MergeableSelector: Merge rule `span a` with rule on line 62
components/_bar.scss:75 [W] MergeableSelector: Merge rule `.bar .middle` with rule on line 22
components/_bar.scss:126 [W] MergeableSelector: Merge rule `.bar .right` with rule on line 22
components/_bar.scss:169 [W] MergeableSelector: Merge rule `&.active.amutebtn` with rule on line 163
components/_bar.scss:175 [W] …
```
> Fix scss-lint error MergeableSelector.

- static/js/services/translation.js
This PR fixes reverts incorrect changes I made in #170 to the translation api.
> Fix translation variable index for singular and plural translations

- static/js/controllers/mediastreamcontroller.js
- static/js/directives/buddypicturecapture.js
- static/js/directives/settings.js
- static/js/mediastream/usermedia.js
- static/js/services/constraints.js
- static/js/services/mediadevices.js
- static/js/services/screensharing.js
- static/js/services/services.js
- static/partials/screensharedialogff.html
- static/partials/settings.html
Use new mediaDevices service.
Prepare to support video constraints in FF>=38.
Disable HD constraints for Firefox.
> Worked to get screen sharing to FF.

- html/logo.html
- html/main.html
- static/js/app.js
- static/js/controllers/appcontroller.js
- static/js/controllers/controllers.js
- static/js/controllers/mediastreamcontroller.js
- static/js/directives/directives.js
- static/js/directives/ui.js
- static/partials/ui.html
Before refactoring too much regarding URL routing, i decided to take a detour and clean up the huge main controller beast.
> First step in getting rid of the huge mediastreamcontroller.

- doc/CHANNELING-API.txt
- src/app/spreed-webrtc-server/channelling.go
- src/app/spreed-webrtc-server/channelling_api.go
- src/app/spreed-webrtc-server/channelling_api_test.go
- src/app/spreed-webrtc-server/room_manager.go
- src/app/spreed-webrtc-server/room_manager_test.go
- src/app/spreed-webrtc-server/roomworker.go
- src/app/spreed-webrtc-server/roomworker_test.go
- src/app/spreed-webrtc-server/session.go
- static/js/app.js
- static/js/mediastream/api.js
This PR brings room names with room types. The roomid is now different from the room name and generated of both. This means rooms with different types but same name do not conflict.
> Room types

- static/js/libs/pdf/pdf.js
- static/js/libs/pdf/pdf.worker.js
This PR updates pdf.js from 1.0.907 to the latest stable 1.0.1040.
Changes see https://github.com/mozilla/pdf.js/releases/tag/v1.0.1040
> Update pdf.js to 1.0.1040

- static/js/directives/youtubevideo.js
This PR changes the YouTube player to only load the sandboxed iframe when necessary.
> Load YouTube sandbox lazily.

- static/partials/youtubevideo_sandbox.html
This further improves security.
> Setup CSP for YouTube sandbox.

- static/js/directives/youtubevideo.js
- static/js/sandboxes/youtube.js
This was only partially implemented before.
Please make sure to update translations after merging this PR.
> Implement error handling for YouTube playback.

- src/styles/components/_youtubevideo.scss
- static/js/directives/youtubevideo.js
- static/partials/youtubevideo.html
This allows reuse of the directive.
> Don't use "id" selectors in directives.

- server.conf.in
- static/js/directives/youtubevideo.js
- static/js/sandboxes/webodf.js
- static/js/services/sandbox.js
This fixes issues with sandboxed presentations on Firefox. Still issues pending with loading YouTube on Firefox.
> Improve sandbox support for Firefox

- .travis.yml
> Also run "styleshint" and "jshint" on Travis.

- static/js/controllers/appcontroller.js
- static/js/services/playsound.js
- static/partials/settings.html
Supports disabling of sound effects.
> Settings option to control app sounds

- .travis.yml
This will help finding broken dependencies.
> Check GPM setup in Travis.

- static/js/main.js
- static/js/services/alertify.js
- static/js/services/desktopnotify.js
- static/js/services/geolocation.js
My (rather old) jshint 2.4.3 reported two errors which are fixed here.
> Fix some jshint errors

- doc/REST-API.txt
- src/app/spreed-webrtc-server/main.go
at /.well-known/spreed-configuration
> Implemented service discovery .well-known endpoint 

- go/channelling/room_manager.go
- go/channelling/room_manager_test.go
- src/app/spreed-webrtc-server/main.go
This can be used by other services to change the room type for some paths.
> Make the room type configurable through NATS.

- doc/CHANNELING-API.txt
- go/channelling/api/api.go
- go/channelling/api/handle_leave.go
- go/channelling/session.go
Previously it was only possible to leave a room by switching to another
room. This change allows explicitly leaving a room without re-joining.
> Added API to leave a room.

- static/js/controllers/uicontroller.js
- static/partials/buddyactions.html
- static/partials/chatroom.html
In conference rooms, everybody automatically calls each other, so there
is no need for an explicit "Call" button.
> Hide "call" button when in conference rooms.

- src/hooks/pre-commit.hook
- src/i18n/Makefile.am
- src/i18n/helpers/polint.py
- src/i18n/messages-de.po
- src/i18n/messages-ja.po
- src/i18n/messages-ko.po
- src/i18n/messages-ru.po
To make reviews of translation changes easier, I added a script to perform various style checks on .po files. This runs during `make build-i18n` (which is tested by Travis) and also from the commit hook.
> Run automated validation on .po files

- go/channelling/server/config.go
- server.conf.in
- src/styles/components/_social.scss
- static/js/directives/socialshare.js
- static/js/services/rooms.js
- static/partials/socialshare.html
Make sure to rebuild styles & translations after merging.
> Add UI to lock/unlock a room

- Makefile.am
> Don't run target binary before get is run

- static/js/services/roompin.js
Nothing _really_ serious though, as the message was still auto-
filtered by Angular. This would not allow to load remote scripts.
As we still need to show some un-sanitized messages, we can't fix
this in alertify.js directly to force-sanitize all texts.
> Fix XSS in room PIN dialog

- Makefile.am
- README.md
This addresses issues reported in #390.
> Notes and fixes for building on FreeBSD.

- static/js/mediastream/usermedia.js
Since FF 49, the call to gUM only succeeds if both audio and video constraints
can be satisfied, i.e. without a webcam the request fails. This is now handled
gracefully, the available devices enumerated and the gUM request is retried
with updated constraints (fixes #394).
> Handle gUM failures on FF when no audio or video device is available

- src/app/spreed-webrtc-server/main.go
- src/app/spreed-webrtc-server/template.go
- src/app/spreed-webrtc-server/template_test.go
> Bring back Go 1.4 and 1.5 support

- dependencies.tsv
See https://github.com/longsleep/pkac/releases/tag/0.1.0
> Upgrade to "pkac" 0.1.0
